### ISSUE TITLE
OpenScoring instructions are out of date

### ISSUE THREAD

**Issue by mchung** [jpmml/openscoring-heroku#1]
The current instructions are out of date; copying a file to the "pmml" directory doesn't seem to deploy the model.

This returns 200: http://returning-pmml.herokuapp.com/openscoring/model
This returns 403: http://returning-pmml.herokuapp.com/openscoring/model/DecisionTreeIris
This returns 404: http://returning-pmml.herokuapp.com/openscoring/metric/model/DecisionTreeIris

Could this be a routing issue with Jetty/Heroku?

**Comment by vruusmann** [comment]
The Openscoring-Heroku project uses Openscoring version 1.1.5 (see the `pom.xml` file in the root directory for the dependency declaration). So, if you need to debug issues related to it, you need to check out the appropriate Openscoring version first. Please note that the master branch of the Openscoring project contains the 1.2-SNAPSHOT version, which has undergone slight REST API changes. I can see from you log that you are trying to access the `/metric/model/{id}` endpoint which is part of 1.2.X REST API, not 1.1.X REST API.

If you follow the README.md file of the Openscoring-Heroku project step-by-step, you should have the auto-deployment directory (and everything else) working OK.

Once the Openscoring version 1.2.0 is released (perhaps even tomorrow), I will bring Openscoring-Heroku and Openscoring-Openschift projects also up to date.

**Comment by mchung** [comment]
@vruusmann Thanks for clearing that up.

**Comment by mchung** [comment]
And to clarify, I was following the README.md in Openscoring-Heroku to the letter. The 2nd URL `/openscoring/model/DecisionTreeIris` returns 403. Is that expected? (I'm aware of the "admin" being imposed, but the docs mention that's only for for PUT and DELETE, but not GET.)

**Comment by vruusmann** [comment]
All the activities that deal with "raw" PMML documents need privileged access. The reason behind restricting the GET method is that most probably your model is confidential and you don't want the rest of the world to be able to download it freely. Of course, this is behavior could be made configurable one day.

**Comment by vruusmann** [comment]
Openscoring version 1.2.0 is out now, but it cannot be integrated into this project due to some behavioral changes. Most importantly, the `--model-dir` functionality was extracted from the server application to a standalone client application `org.openscoring.client.DirectoryDeployer`.

The correct way of doing things would be to launch the server application as a `web` process, and then the directory deployer application as another `worker` process. Unfortunately, as it turns out, Heroku makes it rather difficult to communicate between processes.

I will probably try to come up with a workaround in Openscoring version 1.2.1.

**Comment by mchung** [comment]
Since Heroku isn't playing well with `--model-dir` I'm thinking of deploying via cURL/PUT instead. Are there methods, perhaps at runtime, to relax the privileged access?

**Comment by vruusmann** [comment]
You could disable security by commenting out the `RolesAllowedDynamicFeature` in class `org.openscoring.service.Openscoring` (in file `openscoring-service/src/main/java/org/openscoring/service/Openscoring.java`, line 70) and rebuilding the project locally. That will give you a new executable JAR file `server-executable-1.2-SNAPSHOT.jar` in directory `openscoring-server/target`.

Place this JAR file into the `lib` folder of your Openscoring-Heroku project. Then, modify the `pom.xml` file so that Heroku won't override it during redeployment, and remove the `--model-dir` command-line option from the `Procfile`.
